### ISSUE TITLE
Exchange MacCready, Ballast, Bugss and QNH: Larus <--> OpenSoar

### ISSUE THREAD

**Issue by Simsys** [OpenSoaring/OpenSoar#2]
We would like to improve the usability of the Larus system. Currently, the above mentioned data points cannot be exchanged between Larus and OpenSoar. This means that the pilot has to enter the data into the instruments several times.

For this reason, we have defined new data points, which [are documented here](https://github.com/larus-breeze/doc_larus/blob/master/documentation/Larus_NMEA_Protocol.md). In particular, this concerns the $PLARS Settings parameters bidirectional section at the end of the specification.

Here is my question: Would it be possible to integrate this data point into OpenSoar? As with other drivers, it should be possible to decide whether the data should be exchanged in one direction or bidirectionally.

Examples can be found in the drivers of XCVario and LX Nav at XCSoar. I look forward to your comments

**Comment by Simsys** [comment]
Nice to hear, thank you very much

**Comment by August2111** [comment]
Hi Simsys, this repository is correct and the right one, August2111/OpenSoar is only for my private development... The public appearance with the public branches, releases, issue tracker, pull requests for OpenSoar I moved to this repository last year.
Unfortunately I worked with very high pressure on a new release for OpenVario und OpenSoar - and so this feature had not the highest priority for me...
As I sad in the next release of OpenSoar I will insert this  - maybe in a prerelease end of next week or - if I have more problems with - at end of february latest!

**Comment by Simsys** [comment]
Thank you for the info

**Comment by August2111** [comment]
This should be included in Version (Pre-)Release v7.42.22.A - and also in the master branch too
