### ISSUE TITLE
Raspi 4 compile error

### ISSUE THREAD

**Issue by denis-robel** [OpenSoaring/OpenSoar#6]
Hallo,

today I tried to compile OpenSoar directly on Raspi 4.
Compiling fails with following errors. 
I'm not so specialised in coding. Are there some hints?

Best regards Denis

[code]
root@raspberrypi:/home/pi/Downloads/OpenSoar# make TARGET=UNIX DEBUG=n USE_CCACHE=y -j 1
*  TARGET =       UNIX
*  DEBUG =        n
*  USE_CCACHE =   y
PROGRAM_NAME      is OpenSoar
PROGRAM_VERSION   is 7.41.21
GIT_TAG           is tags/opensoar-7.41.21 
Schwerwiegend: Benötigte einen einzelnen Commit
GIT_COMMIT_ID     is 2e08510532 
RELEASE_COMMIT_ID is  
Git commits: HEAD = 2e08510532 vs. RELEASE =  
  LINK    output/UNIX/bin/OpenSoar
src/Renderer/TextRowRenderer.cpp:29: error: undefined reference to 'Canvas::DrawClippedText(PixelPoint, PixelRect const&, std::basic_string_view<char, std::char_traits<char> >)'
src/Renderer/TwoTextRowsRenderer.cpp:39: error: undefined reference to 'Canvas::DrawClippedText(PixelPoint, PixelRect const&, std::basic_string_view<char, std::char_traits<char> >)'
src/Renderer/TwoTextRowsRenderer.cpp:47: error: undefined reference to 'Canvas::DrawClippedText(PixelPoint, PixelRect const&, std::basic_string_view<char, std::char_traits<char> >)'
src/Renderer/TransparentRendererCache.cpp:31: error: undefined reference to 'VirtualCanvas::Create(Canvas const&, PixelSize)'
src/Renderer/TransparentRendererCache.cpp:67: error: undefined reference to 'Canvas::CopyTransparentWhite(PixelPoint, PixelSize, Canvas const&, PixelPoint)'
src/Renderer/TransparentRendererCache.cpp:91: error: undefined reference to 'Canvas::AlphaBlendNotWhite(PixelPoint, PixelSize, Canvas, PixelPoint, PixelSize, unsigned char)'
src/CrossSection/AirspaceXSRenderer.cpp:184: error: undefined reference to 'Canvas::DrawClippedText(PixelPoint, unsigned int, std::basic_string_view<char, std::char_traits<char> >)'
./src/ui/canvas/VirtualCanvas.hpp:20: error: undefined reference to 'VirtualCanvas::Destroy()'
./src/ui/canvas/VirtualCanvas.hpp:28: error: undefined reference to 'VirtualCanvas::Create(Canvas const&, PixelSize)'
./src/ui/canvas/VirtualCanvas.hpp:20: error: undefined reference to 'VirtualCanvas::Destroy()'
./src/ui/canvas/VirtualCanvas.hpp:20: error: undefined reference to 'VirtualCanvas::Destroy()'
./src/ui/canvas/VirtualCanvas.hpp:20: error: undefined reference to 'VirtualCanvas::Destroy()'
./src/ui/canvas/VirtualCanvas.hpp:28: error: undefined reference to 'VirtualCanvas::Create(Canvas const&, PixelSize)'
./src/ui/canvas/VirtualCanvas.hpp:28: error: undefined reference to 'VirtualCanvas::Create(Canvas const&, PixelSize)'
src/Startup.cpp:337: error: undefined reference to 'UI::TopWindow::CheckResize()'
src/Dialogs/Settings/Panels/LayoutConfigPanel.cpp:323: error: undefined reference to 'UI::TopWindow::CheckResize()'
src/Dialogs/Task/Manager/TaskMapButtonRenderer.cpp:67: error: undefined reference to 'Canvas::Copy(Canvas const&)'
./src/ui/canvas/memory/Canvas.hpp:366: error: undefined reference to 'Canvas::CopyOr(PixelPoint, PixelSize, ConstImageBuffer<BGRAPixelTraits>, PixelPoint)'
./src/ui/canvas/memory/Canvas.hpp:333: error: undefined reference to 'Canvas::Stretch(PixelPoint, PixelSize, ConstImageBuffer<BGRAPixelTraits>, PixelPoint, PixelSize)'
src/MapWindow/MapWindowGlideRange.cpp:410: error: undefined reference to 'Canvas::CopyTransparentWhite(PixelPoint, PixelSize, Canvas const&, PixelPoint)'
./src/ui/canvas/AnyCanvas.hpp:18: error: undefined reference to 'VirtualCanvas::VirtualCanvas(PixelSize)'
./src/ui/canvas/AnyCanvas.hpp:18: error: undefined reference to 'VirtualCanvas::VirtualCanvas(PixelSize)'
src/Form/Edit.cpp:303: error: undefined reference to 'Canvas::DrawClippedText(PixelPoint, unsigned int, std::basic_string_view<char, std::char_traits<char> >)'
src/ui/canvas/Icon.cpp:58: error: undefined reference to 'Bitmap::LoadStretch(ResourceId, unsigned int)'
src/ui/canvas/Icon.cpp:108: error: undefined reference to 'Canvas::CopyOr(PixelPoint, PixelSize, Bitmap const&, PixelPoint)'
src/ui/canvas/Icon.cpp:109: error: undefined reference to 'Canvas::CopyAnd(PixelPoint, PixelSize, Bitmap const&, PixelPoint)'
src/ui/canvas/Icon.cpp:131: error: undefined reference to 'Canvas::CopyNotOr(PixelPoint, PixelSize, Bitmap const&, PixelPoint)'
src/ui/canvas/Icon.cpp:134: error: undefined reference to 'Canvas::CopyAnd(PixelPoint, PixelSize, Bitmap const&, PixelPoint)'
src/ui/window/BufferWindow.cpp:49: error: undefined reference to 'Canvas::Copy(Canvas const&)'
src/ui/window/DoubleBufferWindow.cpp:66: error: undefined reference to 'Canvas::Copy(Canvas const&)'
collect2: error: ld returned 1 exit status
make: *** [build/main.mk:696: output/UNIX/bin/OpenSoar] Fehler 1
[/code]

**Comment by denis-robel** [comment]
It seems that I had a "wasted" copy of the the branch...
I removed the OpenSoar directory completely and cloned it fresh then everything compiles as expected.

**Comment by lordfolken** [comment]
Perfect,  thx for reporting.
